services:
  py-runner:
    build: ./runners/python
    network_mode: "none"
    volumes:
      - ./_work:/work:rw
    working_dir: /work

  ts-runner:
    build: ./runners/typescript
    network_mode: "none"
    volumes:
      - ./_work:/work:rw
    tmpfs:
      - /tmp:mode=1777
    working_dir: /work

  go-runner:
    build: ./runners/go
    network_mode: "none"
    volumes:
      - ./_work:/work:rw
    working_dir: /work
